# Matts Custom Ban Editer Configuration File

ban-format: "&c{prefix} banned {player} for {reason}"

override-ban-screen: true

messages:
  no-permission: "&cYou do not have permission to edit ban messages."
  player-not-found: "&cPlayer not found."
  ban-updated: "&aBan message updated for {player}."

